### ISSUE TITLE
Correcting error : Attempted to access undefined attribute

### ISSUE THREAD

**Issue by schwab** [FalkorDB/FalkorDB#589] opened 2024-03-06 22:06 UTC
After importing a number of new records, we recently started getting an error we never saw before. For this simple query  we are getting the following error:
``` 
graph.query graph:master_data_sch "MATCH (f:fact_master_data_sch) RETURN f.hash_value as hash_value"


> Attempted to access undefined attribute
```
What is the best way to locate or identify nodes that DO NOT have a particular attribute to clean or investigate this error further?  In our case we have > 250K nodes of that type, yet something is apparently creating nodes without the attribute.

**Comment by swilly22** [comment] 2024-03-06 22:16
@schwab, do you have a simple way of replicating this issue,
FalkorDB will return `NULL` when trying to access a none existing attribute

Here's an example:

```
27.0.0.1:6379> GRAPH.QUERY g "create ()"
) 1) "Nodes created: 1"
  2) "Cached execution: 0"
  3) "Query internal execution time: 1.204875 milliseconds"
27.0.0.1:6379> GRAPH.QUERY g "match (a) return a.v as v"
) 1) "v"
) 1) 1) (nil)
) 1) "Cached execution: 0"
  2) "Query internal execution time: 0.719458 milliseconds"
```

Looking at the source code there are only two ways to get this error you've shared:
1. Trying to access an entity before it is committed to the graph.
2. Trying to perform a vector search on a none existing attribute.

Is it possible that a vector search is being performed on a none existing attribute?

**Comment by schwab** [comment] 2024-03-06 22:45
What you said on point 1 made me look more closely at the code.  So, we are deleting a large number of nodes > 100K  with millions of relationships in a chunked loop like the following.  Then, right after this code, we do the query I posted before. If this unwind/delete process is still "running" on the graph after the loop exists in parallel, it could lead to what you described.

```
for i in range(0, len(l_update_hash), chunk_size):
                chunk = l_update_hash[i:i + chunk_size]
                qry = f"UNWIND {chunk} AS hashes MATCH (f:{self.node_type}) WHERE f.hash_value = hashes DELETE f"
                result = self.graph.query(qry)
                removed_count += result.nodes_deleted
```
Is it possible that falkordb is doing the batch of deletes asynchronously?

**Comment by swilly22** [comment] 2024-03-07 05:58
Thank you,
Is it possible that the `chunk` array might contain duplicates ?

**Comment by swilly22** [comment] 2024-03-07 08:36
@schwab,
let me suggest rewriting this query as follows:
```cypher
MATCH (f:{self.node_type})
WHERE f.hash_value IN $hashes
DELETE f
```

Please note that hashes is passed as a Cypher query parameter, as follows:

```python
for i in range(0, len(l_update_hash), chunk_size):
                chunk = l_update_hash[i:i + chunk_size]
                qry = f"MATCH (f:{self.node_type}) WHERE f.hash_value IN $hashes DELETE f"
                result = self.graph.query(qry, {'hashes': chunk})
                removed_count += result.nodes_deleted
```

**Comment by swilly22** [comment] 2024-03-07 17:06
We’ve been able to reproduce the issue, will update on our progress

**Comment by schwab** [comment] 2024-03-07 19:26
OK. A couple more details in case it helps.

- The property that this happens on is an indexed property (but not a vector index)
  - all of our nodes have this same property so it's used as a globally unique index 
- nodes are linked together using their hash_value as a key like so...
```
MATCH (f:fact_master_data_sch),(d:dim_surgeon_fellow) WHERE f.hash_value in ['6d2c5fb84dc98517447bc7d895803c39', 'dc7621c91c64a2bc1dfadd94a3858156', '47aa309ad209fbd08d164eb2692f3959', 'e7fc3d793bc30b72438aed94215f32f5', 'ce8ea990104b0ad13797d346ac572121', '1a78d828b3ec584e8c2df1eb446e2b75', '5d4044ef0e02858a0f76a6176f4eb035', 'cabf32b731da3e270076ba38d045845f', '7b1eaf8fb1962fb05b4400aecb6ee005', '5bae363eeac7c26d130debf9069aaee9', '53e947cca9a33c3e247264991ad94c40', '7bf5caca1c0ef332c56d7b3ab8c1b1b2', '281c340342f3c0b76245c37a06aa0970', '44f00430a0ed352bd891eebb7dbf27b1', 'e6e686e8e981c2bcf6afae1549a89614', '67ec683ea7d5a8996b32c6c0fd17db9a', '77786d1d137dd8268d05ca3387f42a67', '2cdb76ab6dfad2c86e2277cca8e7cbf6', '3cb3eef47f1c346b4db84e6b21f1efb6', 'dae8b785ca70c1d44811033a3bec5ee4', '1f0920f8d99cff9dfd7286a57d7f3688', '4a4d9de504b5417c1ac36ffa5b50d9d0', '0d440cab6dae8232569b0f2468397ae5', '16b6eaa30236c57271b80a08eafe8a8c', '48ef70bdb86343c17484a2649a1e7c99', '60aaa1b7efcebadc1fa5c85b5f6d4863', '9034b6d46d6c658c50b40c396aa030c7', 'c48f9eb508b5e6683facdd2835a10e6c', 'cb1ddd186d29a0d0eb8b3b99a771b4b1', '87459df0243a6a58ac8b8d04b02f6577', 'd498c0bdb69d24177f644398aad33b7c', '4b41d53b9a83427cf7deb8cc10402986', '8f674d84ea9ff520d196bc7fb4ad44c1', 'f12cafe0a930379f4ddf5eb20746decf', '04873687f7b75ab624d3865292eaf687', 'd1b282edc25dd1368836b96e0c2c38b3', '2e76389d732f871241eb7bea2536e228', '4786576d13c7077368864d2eca93dad1', '0642c4d55b566607b62f71021c569947', 'b5a556f6c8a86b13ed890cd3fb7c01d3', '755c22c395accb1871a5ddf7ce3fedf3', '0effdd19426613198fddba9425e3bbd1', '32a70d71d529ed5137415dfc313927e4'] and d.hash_value = 'f035a05884b69de99f0525e1a008b902' CREATE (f)-[:link]->(d)" 
```
(Which links a list of cases to a specific surgeon_fellow)
So, when we perform the deletes above on a list of facts(cases) you can imagine that each delete has a cascade affect of also deleting many relationships. There are about a dozen other dimensions (besides surgeon_fellow) and some of them are many-to-many so the number of actual links deleted per case can be large.

**Comment by swilly22** [comment] 2024-03-09 07:32
Thanks, after investigation we believe the issue is within the GraphBLAS library, we've reached out to the project owner and are waiting for a response.

**Comment by swilly22** [comment] 2024-03-21 06:29
@schwab, Tim had confirmed the issue from his end, he already has a fix for it.
We're waiting for a new GraphBLAS version to be released, I'm not expecting this to take much longer.

**Closed as completed** 2024-03-25 12:49 UTC
